<?php

/*
 * Copyright 2012 Patrick Strobel.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * @author Patrick Strobel
 * @license http://www.apache.org/licenses/LICENSE-2.0  Apache License, Version 2.0
 * @link http://code.google.com/p/googlecharttools-php
 * @version 0.1.0
 * @package default
 */

namespace googlecharttools\view;

/**
 * The ChartManager manages all charts that will be displayed on the page.
 *
 * The ChartManager is responsible for the generation of the correct header-code
 * that has to been inserte into the page's <head> element. The purpose
 * of this code is to contact the Google server to fetch all required, external
 * JavaScript code used to render the charts. It also contains code, that will
 * assign the data and options to the charts and to create the chart itselfs.
 *
 * @package view
 */
class ChartManager {

    /** @var Chart[] */
    private $charts = array();

    /**
     * Adds another chart to the manager.
     *
     * All charts that should be shown on the page have to be added to the manager.
     * Please make sure, that all chart have their own ID. If a chart having the
     * same ID as a chart that has been added before is added, the "older" chart will be
     * overwritten.
     *
     * @param Chart $chart
     *              Chart, that will be displayed on the page
     */
    public function addChart(Chart $chart) {
        $this->charts[$chart->getId()] = $chart;
    }

    /**
     * Genarates the JavaScript code that will be prepare all charts.
     *
     * This code will generate a preparation JavaScript-function for all chart
     * that have been added. This functions will assign the chart's data, options and the
     * charts itselve to a global variable.
     * The code generated code will also contain the required code to load the
     * packages from Google's server and a callback method that will prepare and
     * render all charts automatically as soon as all packages have been loaded.
     *
     * @return string
     *              The generated JavaScript code
     * @throws CodeGenerationException
     *              Thrown, if the JavaScript code coudn't be generated, because
     *              no data ({@link Chart::setData()}) has been assigned to at
     *              least one chart
     */
    public function getJavaScriptCode() {
        $code = "google.load(\"visualization\", \"1\", {packages:[\"corechart\"]});\n" .
                "google.setOnLoadCallback(chartsOnLoad);\n\n";

        // On load callback function
        $code .= "/**\n" .
                " * Callback function used to prepare and automatically draw the charts\n" .
                " */\n" .
                "function chartsOnLoad() {\n";

        foreach ($this->charts as $chart) {
            $id = $chart->getId();
            // Prepare
            $code .= "  " . $id . "ChartPrepare();\n";

            // Draw
            $code .= "  " . $id . "Chart.draw(" . $id . "Data, " . $id . "Options);\n";
        }

        $code .= "}\n\n" .
                "// Chart preparation code\n" .
                "// ----------------------\n\n";
        foreach ($this->charts as $chart) {
            $code .= $chart->getJavaScriptCode() . "\n\n";
        }

        return $code;
    }

    /**
     * Encapsulates the code generated by {@link getJavaScriptCode()} in a valid HTML-code.
     *
     * The generated code is encapsulated in a <script> element.
     *
     * @param boolean $loadJsapi
     *                  If set to true, a <script> element that loads Google's
     *                  JSAPI will be included in the first code-line, too.
     * @return string
     *                  The generated HTML-/JavaScript code. This can be directly
     *                  included in the HTML-page's <head> element.
     * @throws CodeGenerationException
     *              Thrown, if the JavaScript code coudn't be generated, because
     *              no data ({@link Chart::setData()}) has been assigned to at
     *              least one chart
     */
    public function getHtmlHeaderCode($loadJsapi = true) {
        if ($loadJsapi) {
            $code = "<script type=\"text/javascript\" src=\"https://www.google.com/jsapi\"></script>\n";
        }
        $code .= "<script type=\"text/javascript\">\n";
        $code .= $this->getJavaScriptCode();
        $code .= "</script>\n";
        return $code;
    }

}

?>
